accessing
style ^
'
body { 
	width: 70%;
	margin: 0 auto;
}
a { 
	cursor: pointer;
}
.header { 
	width: 100%;
	margin: 0 auto;
}
.task { 
	font-size: 20px;
	margin-bottom: 25px;
}
.note-link { 
      margin-top: 10px;
	border-bottom: 1px solid lightblue;
}
.note-input {  
	display: none;
	margin-top:10px;
}
.btn {  
	margin-top: 15px;
	margin-right: 15px;
}
.note {  
	background-color: white;
	font-size: 16px;
	padding: 2px 10px;
}	
.fa-remove { 
	display: none; 
	color: lightgray;
}	
.fa-remove:hover {  
	display: inline;
}
'	