hooks
style ^
'
body { 
	width: 70%;
	margin: 0 auto;
}
a { 
	cursor: pointer;
}
.header { 
	border-bottom: 2px solid lightblue;
}
.info-t { 
	display: block;
	margin-bottom: 10px;
}
.info-toggle { 
	border-bottom: 1px solid lightblue;
}
.changeColor { 
	color: red;
}
.form-block { 
	margin-top: 10px;
	margin-bottom: 10px;
}
.save-button { 
	margin-left: 20px;
}
.getEmail { 
	margin-left: 20px;
}
.hide { 
	display: none;
}
table { 
	border-collapse: collapse;
}
table, th, td { 
	border: 1px solid lightgray;
}
.th-row { 
	background-color: lightblue;
}
th { 
	padding: 5px 5px;
}
td { 
	padding: 7px 7px;
}
.tasklist { 
	border-bottom: 1px solid lightblue;
}
.taskblock { 
	margin-top: 10px;
	margin-bottom: 20px;
}
.task_data { 
	padding: 5px 30px; 
}
.update-time { 
	border-bottom: 1px solid lightblue;
}
'